# Generated by Django 6.0.7 on 2026-07-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_department_alter_sale_sold_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_code',
            field=models.CharField(default='GEN', help_text='e.g. TRN for Training Kits, ELC for Electronics', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
