# Generated by Django 6.0.7 on 2026-07-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category_short_code_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='short_code',
            field=models.CharField(default='GEN', help_text='e.g. TRN for Training Kits', max_length=10, unique=True),
        ),
    ]
